#!/usr/bin/env bun

import { existsSync, readFileSync, statSync } from "node:fs";
import { extname, isAbsolute, join, relative, resolve } from "node:path";

const rootDir = import.meta.dir;
const indexHtmlPath = join(rootDir, "index.html");
const appEntry = join(rootDir, "src", "app.ts");
const publicAssetDir = join(rootDir, "src");
const publicAssetExtensions = new Set([
	".css",
	".png",
	".jpg",
	".jpeg",
	".gif",
	".webp",
	".svg",
	".ico",
	".avif",
]);
const port = Number(process.env.PORT ?? "3000");

let cachedBundle: { code: string; mtimeMs: number } | null = null;

async function buildAppBundle(): Promise<string> {
	const mtimeMs = statSync(appEntry).mtimeMs;
	if (cachedBundle && cachedBundle.mtimeMs === mtimeMs) {
		return cachedBundle.code;
	}

	const result = await Bun.build({
		entrypoints: [appEntry],
		target: "browser",
		format: "esm",
		sourcemap: "inline",
	});

	if (!result.success || result.outputs.length === 0) {
		const logs = result.logs
			.map((log) => String((log as { message?: unknown }).message ?? log))
			.join("\n");
		console.error("Axiom starter build failed:\n", logs);
		throw new Error(`Failed to build src/app.ts${logs ? `\n${logs}` : ""}`);
	}

	const output = result.outputs[0];
	if (!output) {
		throw new Error("No outputs generated by Bun.build for src/app.ts");
	}

	const code = await output.text();
	cachedBundle = { code, mtimeMs };
	return code;
}

function resolvePublicAsset(pathname: string): string | null {
	const relativePath = decodeURIComponent(pathname).replace(/^\/+/, "");
	if (!relativePath.startsWith("src/")) return null;

	const filePath = resolve(rootDir, relativePath);
	const rel = relative(publicAssetDir, filePath);
	if (rel === "" || rel.startsWith("..") || isAbsolute(rel)) return null;
	if (!publicAssetExtensions.has(extname(filePath).toLowerCase())) return null;
	if (!existsSync(filePath) || !statSync(filePath).isFile()) return null;

	return filePath;
}

function serveStaticFile(filePath: string): Response {
	const file = Bun.file(filePath);
	return new Response(file, {
		headers: {
			"Content-Type": file.type || "application/octet-stream",
		},
	});
}

const server = Bun.serve({
	port,
	async fetch(req) {
		const url = new URL(req.url);
		if (url.pathname === "/") {
			const html = readFileSync(indexHtmlPath, "utf8");
			return new Response(html, {
				headers: { "Content-Type": "text/html; charset=utf-8" },
			});
		}
		if (url.pathname === "/src/app.ts") {
			try {
				const code = await buildAppBundle();
				return new Response(code, {
					headers: { "Content-Type": "application/javascript; charset=utf-8" },
				});
			} catch (error) {
				const message =
					error instanceof Error ? error.message : "Unknown build error";
				const errorPayload = [
					`console.error(${JSON.stringify("Axiom build failed. Check server console for details.")});`,
					`throw new Error(${JSON.stringify(message)});`,
				].join("\n");

				return new Response(errorPayload, {
					status: 500,
					headers: { "Content-Type": "application/javascript; charset=utf-8" },
				});
			}
		}

		const publicAsset = resolvePublicAsset(url.pathname);
		if (publicAsset !== null) {
			return serveStaticFile(publicAsset);
		}

		return new Response("Not Found", { status: 404 });
	},
});

console.log(`🚀 Axiom starter dev server → ${server.url}`);
