import { describe, test, expect, afterEach } from 'bun:test'
import { mkdtemp, rm, readFile, stat } from 'node:fs/promises'
import { isAbsolute, join } from 'node:path'
import { tmpdir } from 'node:os'
import type { BuildConfig, BuildOutput } from 'bun'
import { buildStatic } from '../src/build.js'
import { defineComponent } from '../src/index.js'
import { h } from '../src/syntax/h.js'

// ============================================================
// Helpers
// ============================================================

/** Create a minimal component for testing. */
function makeComponent(content: string) {
  return defineComponent(() =>
    h('div', {}, content)
  )
}

let testDir = ''

async function freshDir(label: string): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), `axiom-build-test-${label}-`))
  testDir = dir
  return dir
}

afterEach(async () => {
  if (testDir) {
    await rm(testDir, { recursive: true, force: true }).catch(() => {})
    testDir = ''
  }
})

// ============================================================
// Tests
// ============================================================

describe('buildStatic()', () => {
  // ---- Filesystem output ----

  test('2.0 bundles assets with Bun.build defaults', async () => {
    const outDir = await freshDir('assets-bundle')
    const fakeOutputPathJs = join(outDir, 'assets', 'entry.js')
    const fakeOutputPathCss = join(outDir, 'assets', 'entry.css')

    const originalBuild = Bun.build
    const buildMock = async (): Promise<BuildOutput> => ({
      success: true,
      logs: [],
      outputs: [
        { path: fakeOutputPathJs },
        { path: fakeOutputPathCss },
      ],
    } as unknown as BuildOutput)
    const calls: BuildConfig[] = []

    Bun.build = async (options: BuildConfig): Promise<BuildOutput> => {
      calls.push(options)
      return buildMock()
    }

    try {
      const result = await buildStatic({
        routes: [{ path: '/', component: makeComponent('Home with assets') }],
        outDir,
        assets: {
          entrypoints: ['fake-entry.ts'],
        },
      })

      expect(calls).toHaveLength(1)
      expect(calls[0]).toEqual({
        entrypoints: ['fake-entry.ts'],
        outdir: join(outDir, 'assets'),
        target: 'browser',
        minify: true,
      })
      expect(result.files).toEqual(
        expect.arrayContaining([fakeOutputPathJs, fakeOutputPathCss]),
      )

      const manifest = JSON.parse(await readFile(join(outDir, 'asset-manifest.json'), 'utf8'))
      expect(manifest.files).toEqual(
        expect.arrayContaining([fakeOutputPathJs, fakeOutputPathCss]),
      )
    } finally {
      Bun.build = originalBuild
    }
  })

  test('2.1 writes files to outDir', async () => {
    const outDir = await freshDir('basic')
    const result = await buildStatic({
      routes: [{ path: '/', component: makeComponent('Home') }],
      outDir,
    })

    expect(result.routes).toBe(1)
    expect(result.files.length).toBeGreaterThan(0)
    expect(result.durationMs).toBeGreaterThanOrEqual(0)

    // index.html at root
    const htmlStat = await stat(join(outDir, 'index.html'))
    expect(htmlStat.isFile()).toBe(true)

    // manifest
    const manifestStat = await stat(join(outDir, 'asset-manifest.json'))
    expect(manifestStat.isFile()).toBe(true)
  })

  // ---- HTML correctness ----

  test('2.2 HTML contains doctype and data-axiom-id', async () => {
    const outDir = await freshDir('html')
    await buildStatic({
      routes: [{ path: '/', component: makeComponent('Test') }],
      outDir,
    })

    const html = await readFile(join(outDir, 'index.html'), 'utf8')
    expect(html.startsWith('<!DOCTYPE html>')).toBe(true)
    expect(html).toContain('data-axiom-id=')
  })

  test('2.2 injects title and description metadata', async () => {
    const outDir = await freshDir('meta')
    await buildStatic({
      routes: [
        {
          path: '/',
          component: makeComponent('Page'),
          metadata: {
            title: 'Axiom SSG',
            description: 'Static site generated by axiom',
          },
        },
      ],
      outDir,
    })

    const html = await readFile(join(outDir, 'index.html'), 'utf8')
    expect(html).toContain('<title>Axiom SSG</title>')
    expect(html).toContain('name="description"')
    expect(html).toContain('content="Static site generated by axiom"')
  })

  // ---- Multiple routes ----

  test('2.4 multiple routes produce separate HTML files', async () => {
    const outDir = await freshDir('multi')
    const result = await buildStatic({
      routes: [
        { path: '/', component: makeComponent('Home') },
        { path: '/about', component: makeComponent('About') },
        { path: '/contact', component: makeComponent('Contact') },
      ],
      outDir,
    })

    expect(result.routes).toBe(3)

    const homeStat = await stat(join(outDir, 'index.html'))
    expect(homeStat.isFile()).toBe(true)

    const aboutStat = await stat(join(outDir, 'about', 'index.html'))
    expect(aboutStat.isFile()).toBe(true)

    const contactStat = await stat(join(outDir, 'contact', 'index.html'))
    expect(contactStat.isFile()).toBe(true)

    const aboutHtml = await readFile(join(outDir, 'about', 'index.html'), 'utf8')
    expect(aboutHtml).toContain('About')

    const contactHtml = await readFile(join(outDir, 'contact', 'index.html'), 'utf8')
    expect(contactHtml).toContain('Contact')
  })

  // ---- Edge cases ----

  test('2.5 rejects route traversal outside outDir', async () => {
    const outDir = await freshDir('invalid-route')

    await expect(
      buildStatic({
        routes: [{ path: '/../outside', component: makeComponent('Escape') }],
        outDir,
      })
    ).rejects.toThrow('Invalid route path: /../outside')
  })

  test('2.5 surfaces Bun.build logs on asset bundling failure', async () => {
    const outDir = await freshDir('bundle-failure')
    const originalBuild = Bun.build

    Bun.build = async (): Promise<BuildOutput> => ({
      success: false,
      logs: [
        { level: 'error', message: 'Failed to bundle entrypoint /index.ts' },
        { level: 'error', message: 'ReferenceError: window is not defined' },
      ],
      outputs: [],
    } as unknown as BuildOutput)

    try {
      await expect(
        buildStatic({
          routes: [{ path: '/', component: makeComponent('Home') }],
          outDir,
          assets: { entrypoints: ['fake-entry.ts'] },
        })
      ).rejects.toThrow(
        'buildStatic: JS bundle failed.\nFailed to bundle entrypoint /index.ts\nReferenceError: window is not defined'
      )
    } finally {
      Bun.build = originalBuild
    }
  })

  test('2.5 empty routes array produces only the manifest', async () => {
    const outDir = await freshDir('empty')
    const result = await buildStatic({
      routes: [],
      outDir,
    })

    expect(result.routes).toBe(0)
    // Only the manifest should be written
    expect(result.files).toHaveLength(1)
    expect(result.files[0]).toContain('asset-manifest.json')

    const manifest = JSON.parse(await readFile(join(outDir, 'asset-manifest.json'), 'utf8'))
    expect(manifest.routes).toEqual([])
    expect(manifest.files).toHaveLength(1)
  })

  test('2.5 route with special characters in path', async () => {
    const outDir = await freshDir('special')
    // Nested path
    await buildStatic({
      routes: [{ path: '/blog/hello-world', component: makeComponent('Post') }],
      outDir,
    })

    const fileStat = await stat(join(outDir, 'blog', 'hello-world', 'index.html'))
    expect(fileStat.isFile()).toBe(true)
  })

  test('2.5 route without metadata does not throw', async () => {
    const outDir = await freshDir('nometa')
    await expect(
      buildStatic({
        routes: [{ path: '/', component: makeComponent('No Meta') }],
        outDir,
      })
    ).resolves.toBeDefined()

    const html = await readFile(join(outDir, 'index.html'), 'utf8')
    expect(html).toContain('<!DOCTYPE html>')
  })

  // ---- Asset manifest ----

  test('manifest lists all generated files', async () => {
    const outDir = await freshDir('manifest')
    const result = await buildStatic({
      routes: [
        { path: '/', component: makeComponent('A') },
        { path: '/page', component: makeComponent('B') },
      ],
      outDir,
    })

    const manifest = JSON.parse(await readFile(join(outDir, 'asset-manifest.json'), 'utf8'))
    expect(manifest.routes).toEqual(['/', '/page'])
    // files in result matches files in manifest (manifest includes itself)
    expect(manifest.files).toEqual(result.files)
    expect(manifest.generated).toBeDefined()
  })

  // ---- BuildResult contract ----

  test('returns correct BuildResult shape', async () => {
    const outDir = await freshDir('result')
    const result = await buildStatic({
      routes: [
        { path: '/', component: makeComponent('A') },
        { path: '/b', component: makeComponent('B') },
      ],
      outDir,
    })

    expect(typeof result.routes).toBe('number')
    expect(Array.isArray(result.files)).toBe(true)
    expect(typeof result.durationMs).toBe('number')
    expect(result.routes).toBe(2)
    expect(result.files.every(file => isAbsolute(file))).toBe(true)
    // 2 HTML files + 1 manifest
    expect(result.files).toHaveLength(3)
  })
})
